
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Sep 12 04:09:00 CEST 2022
//----------------------------------------------------

package compiler.syntax;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int DIDENTIFICADORES = 33;
  public static final int ALTERNATIVASI = 20;
  public static final int FINPROGRAMA = 34;
  public static final int PARAMETROVALOR = 24;
  public static final int STARTIF = 4;
  public static final int ENTERO = 8;
  public static final int BCONSTANTES = 35;
  public static final int CIERTO = 27;
  public static final int RANGO = 2;
  public static final int DECLAREFUNCION = 16;
  public static final int FINBLOQUESENTENCIAS = 9;
  public static final int COMIENZO = 38;
  public static final int COMIENZOBUCLEPARA = 11;
  public static final int IGUALDAD = 19;
  public static final int ESCRIBIR = 36;
  public static final int NUM = 37;
  public static final int SUMA = 30;
  public static final int EOF = 0;
  public static final int PRODUCTO = 29;
  public static final int error = 1;
  public static final int COMIENZOSUBPROGRAMAS = 31;
  public static final int DECLVECTOR = 14;
  public static final int DECLVARIABLES = 21;
  public static final int PIZQUIERDO = 25;
  public static final int ASIGNACION = 43;
  public static final int MENORQUE = 42;
  public static final int FRETURN = 6;
  public static final int ASIGNACIONVECTOR = 3;
  public static final int COMIENZOPROGRAMA = 7;
  public static final int IDEN = 18;
  public static final int FALSO = 23;
  public static final int PDERECHO = 26;
  public static final int CDERECHO = 17;
  public static final int BOOLEANO = 12;
  public static final int STRING = 22;
  public static final int DSENTENCIAS = 41;
  public static final int NOLOGICO = 5;
  public static final int DELIMFUNC = 40;
  public static final int COMIENZOPROCEDIMIENTO = 10;
  public static final int YLOGICA = 39;
  public static final int COMIENZOSI = 13;
  public static final int CIZQUIERDO = 15;
  public static final int RANGOBUCLEPARA = 28;
  public static final int COMIENZODECLTIPOS = 32;
}

